name: SMDMusic
main: me.palapon2545.music.pluginMain
description: Make your own song and Share to player in server!
version: 0.4BETA
authors: [PondJa, Catallena_, DDLoveDew]
website: https://github.com/palapon2545/SMD_Music
commands:
  musicadmin:
       description: See list of helping for admin (OP)
       permission: music.admin
  musicadmin play:
       description: Play Selected Song (OP)
       usage: type /musicadmin play <song> (USE _ FOR SPACING)
       permission: music.admin
  musicadmin random:
       description: Play Random Song (OP)
       usage: type /musicadmin random
       permission: music.admin
  musicadmin list:
       description: List of available song(s) (OP)
       usage: type /musicadmin list
       permission: music.admin
  musicadmin reload:
       description: Re-loading song(s) from folder (OP) [CURRENTLY DISABLE - BUG]
       usage: type /musicadmin reload
       permission: music.admin
  music:
       description: Toggle between Mute and Unmute Music
       usage: type /music
  music info:
       description: Show currently song's information
       usage: type /music info
  music status:
       description: Check that player mute or unmute
       usage: type /music status
  